### ISSUE TITLE
No functional windows build?

### ISSUE THREAD

**Issue by StrikerTheHedgefox** [jhelwig/sd2snes-lttp-rando-tracker#1304]
I tried to get the windows build in the releases page, but it's a corrupted 48 byte zip file. I tried to get a debug build from the actions page, and I just get a blank page when I run it. (QUSB2SNES sees it as being connected, so I'm not sure what's going on)

**Comment by jhelwig** [comment]
Thanks for reporting this! The release files are automatically attached from GitHub Actions, so I'll need to look into what's going on there. It looks like the macOS build also has a similar issue.

**Comment by jhelwig** [comment]
The Windows ZIP file appears to be just the text `./sd2snes-lttp-rando-tracker-windows-release.zip` (while the macOS build is ./sd2snes-lttp-rando-tracker-macos-release.tar.gz). I'll need to poke a things a bit more to see exactly why/how that's happening, and what needs to change to fix it.

If I download one of the debug build artifacts for Windows, it brings up the map & item list if I go to `http://localhost:8000/ui/`. Apparently I forgot to document that the UI was moved to that URL, and forgot to add a redirect from `/` to `/ui/`. I'll update the Readme, and add that redirect.

**Comment by jhelwig** [comment]
Both the missing redirect, and the bad release artifacts should be fixed in the latest release: https://github.com/Technosorcery/sd2snes-lttp-rando-tracker/releases/tag/v2.0.1
